import type { Metadata } from 'next';
import '@styles/main.scss';
import { roboto } from '@utils/fonts';
import { TLayoutProps } from '@/types/types';
import Navbar from '@widgets/Navbar/Navbar';
import Footer from '@widgets/Footer/Footer';
import UpButton from '@/widgets/UpButton/UpButton';
import StoreProvider from '../StoreProvider';
import Modal from '@/widgets/Modal/Modal';

export const metadata: Metadata = {
  title: `Draft | TV 2.0`,
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<TLayoutProps>) {
  const { lang } = await params;

  return (
    <StoreProvider lang={lang}>
      <html lang={lang}>
        <body className={roboto.className}>
          <Navbar lang={lang} />
          <main>{children}</main>
          <Footer lang={lang}></Footer>
          <UpButton />
          <Modal />
        </body>
      </html>
    </StoreProvider>
  );
}
