import type { Metadata } from 'next';
import '@/styles/main.scss';
import { roboto } from '../../utils/fonts';
import Navbar from '@/components/Navbar/Navbar';
import LangButton from '@/components/Navbar/LangButton';
// import { getLocales } from '@/locales/locales';

export const metadata: Metadata = {
  title: 'Template for TV 2.0',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'ru' }, { lang: 'en' }];
}

type TProps = {
  children: React.ReactNode;
  params: { lang: string };
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<TProps>) {
  // const t = await getLocales(lang);

  return (
    <html lang={lang}>
      <body className={roboto.className}>
        <Navbar>
          <LangButton />
        </Navbar>
        {children}
      </body>
    </html>
  );
}
