import type { Metadata } from 'next';
import '@/styles/main.scss';
import { roboto } from '../../utils/fonts';
import Navbar from '@/app/components/Navbar/Navbar';
import LangSwitcher from '@/app/components/Navbar/LangSwitcher';
import { TGeneralProps } from '@/types/types';
// import { getLocales } from '@/locales/locales';

export const metadata: Metadata = {
  title: 'Template for TV 2.0',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'ru' }, { lang: 'en' }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<TGeneralProps>) {
  // const t = await getLocales(lang);
  const { lang } = await params;

  // console.log('| ================> RootLayout lang ================>', lang);

  return (
    <html lang={lang}>
      <body className={roboto.className}>
        <Navbar lang={lang}>
          <LangSwitcher lang={lang} />
        </Navbar>
        {children}
      </body>
    </html>
  );
}
