import type { Metadata } from 'next';
import '@/styles/main.scss';
import { roboto } from '../utils/fonts';
import Navbar from '@/components/Navbar/Navbar';
import LangButton from '@/components/Navbar/LangButton';

export const metadata: Metadata = {
  title: 'Template for TV 2.0',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={roboto.className}>
        <Navbar>
          <LangButton />
        </Navbar>
        {children}
      </body>
    </html>
  );
}
